config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

   root 'users#index'
   get 'users/signature' => 'users#signature'
   get '/questions' => 'questions#index'
   post '/questions' => 'questions#create'
   get '/questions/:id/answers' => 'answers#show', as: 'answers'
   post '/questions/:id/answers' => 'answers#create'
   get '/students' => 'users#students', as: 'students'
   get '/tutors' => 'users#tutors', as: 'tutors'
   get '/video' => 'users#video'
   post '/users/:id/reviews' => 'reviews#create'
   get '/profile/:id' => 'users#show', as: 'profile'
   get '/curriculums/ruby' => 'curriculums#ruby', as: 'curriculums_ruby'
   get '/curriculums/jquery' => 'curriculums#jquery', as: 'curriculums_jquery'
   get '/curriculums/angular' => 'curriculums#angular', as: 'curriculums_angular'
   get '/curriculums/sql' => 'curriculums#sql', as: 'curriculums_sql'
   get '/curriculums/git' => 'curriculums#git', as: 'curriculums_git'
    get '/curriculums/subl' => 'curriculums#subl', as: 'curriculums_subl'
    get '/curriculums/fundamentals' => 'curriculums#fundamentals', as: 'curriculums_fund'
    get '/curriculums/heroku' => 'curriculums#heroku', as: 'curriculums_heroku'
    get '/curriculums/html' => 'curriculums#html', as: 'curriculums_html'
    get '/curriculums/css' => 'curriculums#css', as: 'curriculums_css'
    get '/curriculums/javascript' => 'curriculums#javascript', as: 'curriculums_js'
    get '/curriculums/mongo' => 'curriculums#mongo', as: 'curriculums_mongo'
    get '/curriculums/python' => 'curriculums#python', as: 'curriculums_python'
   get '/users/:id/invite' => 'users#invite'
   get '/users/tutors_map' => 'users#tutors_map', as: 'tutors_map'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  has_many :questions
  has_many :answers

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:linkedin]

  has_many :reviewer_relationships, class_name: "Review", foreign_key: "reviewee_id"
  has_many :reviewers, class_name: "User", through: :reviewer_relationships

  has_many :reviewee_relationships, class_name: "Review", foreign_key: "reviewer_id"
  has_many :reviewees, class_name: "User", through: :reviewee_relationships
  has_attached_file :image,
                    :default_url => 'http://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/600px-No_image_available.svg.png'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # has_many :reviewer_relationships, through: :review, foreign_key: :reviewer_id
  # has_many :reviewers, source: :user, through: :reviewer_relationships

  # has_many :reviewee_relationships, through: :review, foreign_key: :reviewee_id
  # has_many :reviewees, source: :user, through: :reviewee_relationships
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require('cine_io')

  # def signature
  #   if current_user
  #     client = CineIo::Client.new(secretKey: ENV['CINE_IO_SECRET_KEY'])
  #     identity = current_user.id
  #     response = client.peer.generate_identity_signature(identity)
  #     render json: response
  #   else
  #     render json: nil
  #   end
  # end

  def students
    @students = User.where(user_type: 1)
  end

  def tutors
    @tutors = User.where(user_type: 2)
  end

  def tutors_map
    @tutors = User.where(user_type: 2)
    render json: @tutors
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.where(reviewee_id: @user.id)
    p @user.email
    p @user.first_name
    render :profile_show
  end

  def video
  end

  def invite
    @user = User.find(params[:id])
    UserMailer.chat_invitation(@user).deliver
    UserMailer.chat_invitation(current_user).deliver
    render json: nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="top-container">
  <title>2TR Online Learning Can be Easier</title>
  <%= render "navs/nav" %>
</div>

<div class="signup-render">
  <%= render "users/registrations/student_signup" %>
</div>

<div class="login-render">
  <%= render "users/confirmations/login" %>
</div>

<div class='tutor-render'>

  <%= render "users/registrations/new" %>

</div>

<div class="hero" style="background-image:url('https://download.unsplash.com/photo-1416339442236-8ceb164046f8')"></div>
<div class="q-container">
  <div class="main-quote">
    A New Way to Learn Coding</br>
    A New Way to Share Knowledge
  </div>
</div>
    <% if user_signed_in? %>
  <% else %>
    <div class="how_to">
      <div class="how_to_1 four columns value-prop">
        <p>Log in or Sign in as a Student/Tutor</p>
        <div class= 'image'>
          <%= image_tag("Image1.jpg") %>
        </div>
      </div>
      <div class="how_to_2 four columns value-prop">
        <p>Enjoy courses we carefully selected</p>
        <div class= 'image'>
        <%= image_tag("Image3.jpg") %>
        </div>
      </div>
      <div class="how_to_3 four columns value-prop">
        <p>Questions? Connect with one of our tutors</p>
        <div class= 'image'>
          <%= image_tag("Image2.jpg") %>
        </div>
      </div>
  <% end %>
</div>

<div class="curriculum-container">
  <div class="main-container">
    <h3 class="c-head">Don't Know Where to Start? Try Courses We carefully Selected</h3>
    <div class="curriculum" id="html">
        <strong>HTML</strong>
    </div>
    <div class="curriculum" id="javascript">
        <strong>Javascript</strong>
    </div>
    <div class="curriculum" id="css">
        <strong>CSS</strong>
    </div>
    <div class="curriculum" id="heroku">
        <strong>Heroku</strong>
    </div>
    <div class="curriculum" id="python">
        <strong>Python</strong>
    </div>
    <div class="curriculum" id="git">
        <strong>Git</strong>
    </div>
    <div class="curriculum" id="ruby">
        <strong>Ruby</strong>
    </div>
    <div class="curriculum" id="fundamentals">
        <strong>APIs</strong>
    </div>
    <div class="curriculum" id="mongo">
        <strong>MongoDB</strong>
    </div>
    <div class="curriculum" id="jquery" id="javascript">
        <strong>jQuery</strong>
    </div>
    <div class="curriculum" id="sublime">
        <strong>Sublime</strong>
    </div>
    <div class="curriculum" id="sql">
        <strong>SQL</strong>
    </div>
    <div class='expend-hidden'></div>
    <% if user_signed_in? %>
    <%= button_to "Have A Question?", questions_path, method: :get, :class => "question_button" %>
    <% else %>
    <% end %>
  </div>
</div>

<%= render "footer/footer" %>

app/views/users/profile_show.html.erb
<div class="profile-container">
  <%= render "navs/login_nav" %>
</div>

<div class='profile-edit'>

</div>
<% if current_user.id == @user.id %>
<div class='edit-profile u-pull-right'>
    <h2>Edit Profile</h2>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= devise_error_messages! %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>

    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Update" %>
    </div>
  <% end %>

  <h3>Cancel my account</h3>

  <p>Unhappy with 2tr? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
  </div>
  <% end %>

  <div class='profile-about'>
    <h2>About <%= @user.first_name %></h2>
    <img src="<%= @user.image %>" height="90" width="110">
    <h5>Email: <%= @user.email %></h5>
    <h5>Description: <%= @user.description %></h5>
    <% if current_user.id == @user.id %>
      <button class='edit_button'>Edit Profile</button>
    <% end %>
  </div>

  <div class="review-container">
    <% if @user.first_name %>
      <h4><%= @user.first_name %>'s Reviews:</h4>
    <% else %>
      <h4><%= @user.email %>'s Reviews:</h4>
    <% end %>
    <% @reviews.each do |review| %>
      <div class="review">
        <p>Review: <%= review.content %></p>
        <p>Rating: <%= '⭐' * review.rating %></p>
      </div>
    <% end %>
  </div>


  <% if current_user.id != @user.id %>
    <button class="review-button" id="<%= @user.id %>">Leave Review for <%= @user.first_name %>
    </button>
  <% end %>

</div>

<script id="review-template" type="text/x-handlebars-template">
  <div class="review">
    <p>Review: {{ content }}</p>
    <p>{{ rating }}</p>
  </div>
</script>

<%= render "footer/footer" %>

app/views/users/show.html.erb
<div id="box_0">
  <div id="container">
      <div id="pic-logo">
      </div>
      <ul id="attributes">
      </ul>
  </div>
</div>

<div id="box_1">
  <div id="container">
      <div id="pic-logo">
      </div>
      <ul id="attributes">
      </ul>
  </div>
</div>

<div id="box_2">
  <div id="container">
      <div id="pic-logo">
      </div>
      <ul id="attributes">
      </ul>
  </div>
</div>

<div id="box_3">
  <div id="container">
      <div id="pic-logo">
      </div>
      <ul id="attributes">
      </ul>
  </div>
</div>


<div id="box_4">
  <div id="container">
    <div id="pic-logo">
    </div>
    <ul id="attributes">
    </ul>
  </div>
</div>

<div id="box_5">
  <div id="container">
    <div id="pic-logo">
    </div>
    <ul id="attributes">
    </ul>
    </div>
  </div>

  <div id="box_6">
  <div id="container">
    <div id="pic-logo">
    </div>
    <ul id="attributes">
    </ul>
    </div>
  </div>

app/views/users/students.html.erb
<!-- Not implemented as of yet -->

<h1>Students</h1>

<div class="user-container">
  <% @students.each do |student| %>
    <div class="user" id="<%= student.id %>">
      <img src="<%= student.url %>" >
      <p><%= student.first_name %></p>
      <p><%= student.description %></p>
      <button class="review">Leave Feedback</button>
    </div>
  <% end %>
</div>

app/views/users/tutors.html.erb
<script src="geocode.js"></script>
<div class="profile-container">
  <%= render "navs/login_nav" %>
</div>
<script>
// Due to Turbolinks, this will be temp solution
  (function()
  {
    if( window.localStorage )
    {
      if( !localStorage.getItem('firstLoad') )
      {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
      else
        localStorage.removeItem('firstLoad');
    }
  })();
  var geocoder;
  var map;
  var infowindow;
  var marker;
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(37.7833, -122.4167);
    var mapOptions = {
      zoom: 8,
      center: latlng
    }
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  }

  function codeAddress() {
    var address = document.getElementById('address').value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  } //codeAddress()

  google.maps.event.addDomListener(window, 'load', initialize);
  $(document).ready(function() {
    $('.tutor-main').on('click', function(evt) {
      evt.preventDefault();
      $.ajax({
        url: '/users/tutors_map',
        type: 'GET',
        dataType: 'JSON'
      })
      .done(function(response) {
        for (var i=0; i<response.length; i++) {
          console.log(response[i].address)
          var marker = new google.maps.Marker({
          position: LatLng(response[i].address),
          map: map,
          title: response[i].first_name
          });
        } //for
      })
      .fail(function() {
        console.log("error");
      }) //fail
    })  //click
  }) //ready

</script>

<div class="splash">
  <div class="tutor-main">
    <form class="postcode u-pull-left">
      Finding Toturs near you?<br />
      <input id="address" type="textbox" value="94070">
      <br>
      <input type="button" value="Search" onclick="codeAddress()">
    </form>
    <div id="map-canvas" class="u-pull-right"></div>
  </div>
</div>

<div class="user-container">
  <% @tutors.each do |tutor| %>
    <div class="user" id="<%= tutor.id %>">
      <img src="<%= tutor.image %>" height="90" width="110">
      <h3 style="color:#CCCCFF"><%= tutor.first_name %></h3>
      <p><%= tutor.description %></p>
      <p>I live in <%= tutor.address %> area</p>
      <button class="invitation">Send chat invitation</button>
      <%= button_to "Profile", profile_path(tutor), method: :get %>
      <div id="chat-inv"></div>
    </div>
  <% end %>
</div>
</div>

app/views/users/video.html.erb
<div class='wrapper debug' >
  <div id='firebase-override' class='debug'>
    <div id='firechat-wrapper' class= 'debug'>
    </div>
  </div>


  <div class="video-screen debug">
  </div>

  <div class='videoz debug'>
    <div>
    <button class="start_video">Start video</button>
    <button class="end_video">End video</button>
    </div>
    <button class="twitter_video" onclick='login()'>Chat login with Twitter</button>
    <%= button_to "home", root_path, method: :get %>
  </div>
</div>

<script>
// Create a new Firebase reference, and a new instance of the Login client
var chatRef = new Firebase('https://shining-torch-9209.firebaseio.com/chat');
function login() {
  chatRef.authWithOAuthPopup("twitter", function(error, authData) {
    if (error) {
      console.log(error);
    }
  });
}
function initChat(authData) {
  var chat = new FirechatUI(chatRef, document.getElementById('firechat-wrapper'));
  chat.setUser(authData.uid, authData[authData.provider].displayName);
}

chatRef.onAuth(function(authData) {
  // Once authenticated, instantiate Firechat with our user id and user name
  if (authData) {
    initChat(authData);
  }
});
</script>