config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

   root 'users#index'
   get 'users/signature' => 'users#signature'
   get '/questions' => 'questions#index'
   post '/questions' => 'questions#create'
   get '/questions/:id/answers' => 'answers#show', as: 'answers'
   post '/questions/:id/answers' => 'answers#create'
   get '/students' => 'users#students', as: 'students'
   get '/tutors' => 'users#tutors', as: 'tutors'
   get '/video' => 'users#video'
   post '/users/:id/reviews' => 'reviews#create'
   get '/profile/:id' => 'users#show', as: 'profile'
   get '/curriculums/ruby' => 'curriculums#ruby', as: 'curriculums_ruby'
   get '/curriculums/jquery' => 'curriculums#jquery', as: 'curriculums_jquery'
   get '/curriculums/angular' => 'curriculums#angular', as: 'curriculums_angular'
   get '/curriculums/sql' => 'curriculums#sql', as: 'curriculums_sql'
   get '/curriculums/git' => 'curriculums#git', as: 'curriculums_git'
    get '/curriculums/subl' => 'curriculums#subl', as: 'curriculums_subl'
    get '/curriculums/fundamentals' => 'curriculums#fundamentals', as: 'curriculums_fund'
    get '/curriculums/heroku' => 'curriculums#heroku', as: 'curriculums_heroku'
    get '/curriculums/html' => 'curriculums#html', as: 'curriculums_html'
    get '/curriculums/css' => 'curriculums#css', as: 'curriculums_css'
    get '/curriculums/javascript' => 'curriculums#javascript', as: 'curriculums_js'
    get '/curriculums/mongo' => 'curriculums#mongo', as: 'curriculums_mongo'
    get '/curriculums/python' => 'curriculums#python', as: 'curriculums_python'
   get '/users/:id/invite' => 'users#invite'
   get '/users/tutors_map' => 'users#tutors_map', as: 'tutors_map'

end

app/views/navs/_login_nav.html.erb
<div id="user_nav" >
   <div class="logged_in">
    <div class="logged_in_nav">
     Welcome <%= current_user.email %>
   </div>
    <div class="logged_in_nav">
      <%= link_to "🏠 Home", root_path %>
    </div>
   <div class="logged_in_nav">
     <%= link_to "👭 Profile", profile_path(current_user) %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "🌎 Find a tutor", tutors_path %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
   </div>
 </div>

app/views/navs/_nav.html.erb
<div id="user_nav" >
   <% if user_signed_in? %>
   <% if session[:linkedin_token].nil? %>
   <div class="logged_in">
    <div class="logged_in_nav">
     Welcome <%= current_user.first_name|| current_user.email %>
   </div>
   <div class="logged_in_nav">
      <%= link_to "🏠 Home", root_path %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "👭 Profile", profile_path(current_user) %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "🌎 Find a tutor", tutors_path %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
   </div>
 </div>
 <% else %>
 <div class="logged_in">
   <div class="logged_in_nav">
     Welcome <%= current_user.first_name || current_user.email %>
   </div>
   <div class="logged_in_nav">
      <%= link_to "🏠 Home", root_path %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "Profile", profile_path(current_user) %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "Find a tutor", tutors_path %>
   </div>
   <div class="logged_in_nav">
     <%= link_to "Sign out", linkedin_logout_path, method: :delete %>
   </div>
 </div>
 <% end %>
 <% else %>
 <div id="not_logged_in">
  <div class="test">
    <a class='tutor_button' href='/users/sign_up'>🎓 Become a Tutor</a>
  </div>
  <div class="test">
    <a class="login">📚 Log In</a>
  </div>
  <div class="test">
    <a class="signup">📖 Student Sign Up</a>
  </div>
</div>
<% end %>